// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.vis.oubl.domain;

import com.vis.oubl.vo.My010CustomerVO;

/**
 * @see My010Customer
 */
public class My010CustomerDaoImpl
    extends My010CustomerDaoBase
{
    /**
     * {@inheritDoc}
     */
    protected My010CustomerVO[] handleQueryAllPatients()
    {
        // TODO implement public My010CustomerVO[] handleQueryAllPatients()
        return null;
}

    /**
     * {@inheritDoc}
     */
    protected My010CustomerVO handleGetPatientByTelephoneNumber(Long telephoneNumber)
    {
        // TODO implement public My010CustomerVO handleGetPatientByTelephoneNumber(Long telephoneNumber)
        return null;
}

    /**
     * {@inheritDoc}
     */
    protected My010CustomerVO handleGetPatientById(Long id)
    {
        // TODO implement public My010CustomerVO handleGetPatientById(Long id)
        return null;
}

    /**
     * {@inheritDoc}
     */
    public void toMy010CustomerVO(
        My010Customer source,
        My010CustomerVO target)
    {
        // TODO verify behavior of toMy010CustomerVO
        super.toMy010CustomerVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    public My010CustomerVO toMy010CustomerVO(final My010Customer entity)
    {
        // TODO verify behavior of toMy010CustomerVO
        return super.toMy010CustomerVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private My010Customer loadMy010CustomerFromMy010CustomerVO(My010CustomerVO my010CustomerVO)
    {
        // TODO implement loadMy010CustomerFromMy010CustomerVO
        throw new UnsupportedOperationException("com.vis.oubl.domain.loadMy010CustomerFromMy010CustomerVO(My010CustomerVO) not yet implemented.");

        /* A typical implementation looks like this:
        My010Customer my010Customer = this.load(my010CustomerVO.getId());
        if (my010Customer == null)
        {
            my010Customer = My010Customer.Factory.newInstance();
        }
        return my010Customer;
        */
    }

    /**
     * {@inheritDoc}
     */
    public My010Customer my010CustomerVOToEntity(My010CustomerVO my010CustomerVO)
    {
        // TODO verify behavior of my010CustomerVOToEntity
        My010Customer entity = this.loadMy010CustomerFromMy010CustomerVO(my010CustomerVO);
        this.my010CustomerVOToEntity(my010CustomerVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void my010CustomerVOToEntity(
        My010CustomerVO source,
        My010Customer target,
        boolean copyIfNull)
    {
        // TODO verify behavior of my010CustomerVOToEntity
        super.my010CustomerVOToEntity(source, target, copyIfNull);
    }

	@Override
	protected My010CustomerVO[] handleQueryAllCustomer() throws Exception {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected My010CustomerVO handleGetCustomerByTelephoneNumber(
			Long telephoneNumber) throws Exception {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected My010CustomerVO handleGetCustomertById(Long id) throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
}