// license-header java merge-point
/* Autogenerated on 11/12/2015 14:47:35+0200 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: customerSearch
 * STEREOTYPE:  WebService on SearchService
 * STEREOTYPE:  WebServiceOperation on customerSearch
*/
package com.vis.oubl.service;

import com.vis.oubl.ServiceLocator;

/**
 * WebService Service Method Implementation for the SearchService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[customerSearch].
 * 
 */

public class CustomerSearchImpl
{
    /**
     * Constructor
     */
    public CustomerSearchImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void customerSearchSetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void customerSearchTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the customerSearch service method parameters on SearchService.
    * 
    * @param id datatype.Integer multiplicity=0..1
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void customerSearchTransformInput(
        final Integer id
    )
    {

        if (id != null)
        {
            // transform(Integer);
        }
    }

   /**
    * Transforms input to an output response for customerSearch service method on SearchService.
    * 
    * @return customerSearchResponse Object
    */
    public static Object customerSearchTransformResponse(
        Integer id
    )


        // throws TransformationException?
    {
	
        // Dummy return value implementation with default values...
        // Iterate down through all complex types and create default dummy constructor and attribute values
		 ServiceLocator locator= ServiceLocator.instance();
		return locator.getMy010CustomerService().getCustomerById((long)id);
      //  Object rtn = new Object();

       // return rtn;
    }

    /** Create input test data for SearchService customerSearch
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * id: Integer
     * @return customerSearchReturn CustomerSearch WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static CustomerSearch customerSearchCreateInput()
    {
        CustomerSearch customerSearchReturn = new CustomerSearch();

        // parameter1 idParam1 with 0 properties:
        Integer idParam1 = Integer.valueOf(1);
        customerSearchReturn.setId(idParam1);

        return customerSearchReturn;
    }
}