// license-header java merge-point
/* Autogenerated on 10/22/2015 20:48:02-0700 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: customersQuery
 * STEREOTYPE:  WebService on SearchService
 * STEREOTYPE:  WebServiceOperation on customersQuery
*/
package com.vis.oubl.service;

/**
 * WebService Service Method Implementation for the SearchService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[customersQuery].
 * 
 */

public class CustomersQueryImpl
{
    /**
     * Constructor
     */
    public CustomersQueryImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void customersQuerySetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void customersQueryTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the customersQuery service method parameters on SearchService.
    * 
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void customersQueryTransformInput(
    )
    {
        // Documented empty block - avoid compiler warning - no method parameters
    }

   /**
    * Transforms input to an output response for customersQuery service method on SearchService.
    * 
    * @return customersQueryResponse Object
    */
    public static Object customersQueryTransformResponse(
        /* Domain response to be transformed to service response */)
        // throws TransformationException?
    {
        // Dummy return value implementation with default values...
        // Iterate down through all complex types and create default dummy constructor and attribute values
        Object rtn = new Object();

        return rtn;
    }

    /** Create input test data for SearchService customersQuery
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * @return customersQueryReturn CustomersQuery WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static CustomersQuery customersQueryCreateInput()
    {
        CustomersQuery customersQueryReturn = new CustomersQuery();

        return customersQueryReturn;
    }
}