// license-header java merge-point
/* Autogenerated on 11/12/2015 14:55:54+0200 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: deleteCustomer
 * STEREOTYPE:  WebService on SearchService
 * STEREOTYPE:  WebServiceOperation on deleteCustomer
*/
package com.vis.oubl.service;

import com.vis.oubl.ServiceLocator;

/**
 * WebService Service Method Implementation for the SearchService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[deleteCustomer].
 * 
 */

public class DeleteCustomerImpl
{
    /**
     * Constructor
     */
    public DeleteCustomerImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void deleteCustomerSetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void deleteCustomerTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the deleteCustomer service method parameters on SearchService.
    * 
    * @param id datatype.Long multiplicity=0..1
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void deleteCustomerTransformInput(
        final Long id
    )
    {

        if (id != null)
        {
            // transform(Long);
        }
    }

   /**
    * Transforms input to an output response for deleteCustomer service method on SearchService.
    * 
    * @return deleteCustomerResponse Integer
    */
    public static Integer deleteCustomerTransformResponse(
        Long id
    )


        // throws TransformationException?
    {
	
        // Dummy return value implementation with default values...
        // Iterate down through all complex types and create default dummy constructor and attribute values
		 ServiceLocator locator= ServiceLocator.instance();
        Integer rtn = Integer.valueOf(1);

        return rtn;
    }

    /** Create input test data for SearchService deleteCustomer
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * id: Long
     * @return deleteCustomerReturn DeleteCustomer WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static DeleteCustomer deleteCustomerCreateInput()
    {
        DeleteCustomer deleteCustomerReturn = new DeleteCustomer();

        // parameter1 idParam1 with 0 properties:
        Long idParam1 = Long.valueOf(1);
        deleteCustomerReturn.setId(idParam1);

        return deleteCustomerReturn;
    }
}