// license-header java merge-point
/* Autogenerated on 11/12/2015 14:55:54+0200 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: updateCustomer
 * STEREOTYPE:  WebService on SearchService
 * STEREOTYPE:  WebServiceOperation on updateCustomer
*/
package com.vis.oubl.service;

import com.vis.oubl.ServiceLocator;
import com.vis.oubl.vo.My010CustomerVO;

/**
 * WebService Service Method Implementation for the SearchService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[updateCustomer].
 * 
 */

public class UpdateCustomerImpl
{
    /**
     * Constructor
     */
    public UpdateCustomerImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void updateCustomerSetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void updateCustomerTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the updateCustomer service method parameters on SearchService.
    * 
    * @param patient My010CustomerVO multiplicity=0..1
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void updateCustomerTransformInput(
        final My010CustomerVO patient
    )
    {

        if (patient != null)
        {
            // transform(My010CustomerVO);
            // property id with 0 properties:
            Long id1 = patient.getId();
            if (id1 != null)
            {
            }
            // property firstName with 0 properties:
            String firstName2 = patient.getFirstName();
            if (firstName2 != null)
            {
            }
            // property lastName with 0 properties:
            String lastName3 = patient.getLastName();
            if (lastName3 != null)
            {
            }
            // property middleName with 0 properties:
            String middleName4 = patient.getMiddleName();
            if (middleName4 != null)
            {
            }
            // property identityNumber with 0 properties:
            Integer identityNumber5 = patient.getIdentityNumber();
            if (identityNumber5 != null)
            {
            }
            // property insuranceNumber with 0 properties:
            Integer insuranceNumber6 = patient.getInsuranceNumber();
            if (insuranceNumber6 != null)
            {
            }
            // property address with 0 properties:
            String address7 = patient.getAddress();
            if (address7 != null)
            {
            }
            // property mobileNumber with 0 properties:
            Long mobileNumber8 = patient.getMobileNumber();
            if (mobileNumber8 != null)
            {
            }
            // property telephoneNumber with 0 properties:
            Integer telephoneNumber9 = patient.getTelephoneNumber();
            if (telephoneNumber9 != null)
            {
            }
            // property nationality with 0 properties:
            String nationality10 = patient.getNationality();
            if (nationality10 != null)
            {
            }
            // property type with 0 properties:
            String type11 = patient.getType();
            if (type11 != null)
            {
            }
        }
    }

   /**
    * Transforms input to an output response for updateCustomer service method on SearchService.
    * 
    * @return updateCustomerResponse Integer
    */
    public static Integer updateCustomerTransformResponse(
        My010CustomerVO patient
    )


        // throws TransformationException?
    {
	
        // Dummy return value implementation with default values...
        // Iterate down through all complex types and create default dummy constructor and attribute values
		 ServiceLocator locator= ServiceLocator.instance();
        Integer rtn = Integer.valueOf(1);

        return rtn;
    }

    /** Create input test data for SearchService updateCustomer
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * patient: My010CustomerVO
     * @return updateCustomerReturn UpdateCustomer WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static UpdateCustomer updateCustomerCreateInput()
    {
        UpdateCustomer updateCustomerReturn = new UpdateCustomer();

        // parameter1 patientParam1 with 11 properties: id firstName lastName middleName identityNumber insuranceNumber address mobileNumber telephoneNumber nationality type
        My010CustomerVO patientParam1 = new My010CustomerVO();
        patientParam1.setId(Long.valueOf(1));
        patientParam1.setFirstName("firstName");
        patientParam1.setLastName("lastName");
        patientParam1.setMiddleName("middleName");
        patientParam1.setIdentityNumber(Integer.valueOf(1));
        patientParam1.setInsuranceNumber(Integer.valueOf(1));
        patientParam1.setAddress("address");
        patientParam1.setMobileNumber(Long.valueOf(1));
        patientParam1.setTelephoneNumber(Integer.valueOf(1));
        patientParam1.setNationality("nationality");
        patientParam1.setType("type");
        updateCustomerReturn.setPatient(patientParam1);

        return updateCustomerReturn;
    }
}