package com.vis.oubl.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-03-19T08:16:52.590+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "MedicalHistoryService", 
                  wsdlLocation = "file:/D:/PAG/PAG-OUBL/mda/../webservice/src/main/webapp/wsdl/MedicalHistoryService.wsdl",
                  targetNamespace = "http://service.oubl.vis.com/") 
public class MedicalHistoryServiceSEIClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.oubl.vis.com/", "MedicalHistoryService");
    public final static QName MedicalHistoryService = new QName("http://service.oubl.vis.com/", "MedicalHistoryService");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/PAG/PAG-OUBL/mda/../webservice/src/main/webapp/wsdl/MedicalHistoryService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MedicalHistoryServiceSEIClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/PAG/PAG-OUBL/mda/../webservice/src/main/webapp/wsdl/MedicalHistoryService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MedicalHistoryServiceSEIClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MedicalHistoryServiceSEIClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedicalHistoryServiceSEIClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MedicalHistoryServiceSEIClient(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MedicalHistoryServiceSEIClient(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MedicalHistoryServiceSEIClient(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MedicalHistoryServiceSEI
     */
    @WebEndpoint(name = "MedicalHistoryService")
    public MedicalHistoryServiceSEI getMedicalHistoryService() {
        return super.getPort(MedicalHistoryService, MedicalHistoryServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedicalHistoryServiceSEI
     */
    @WebEndpoint(name = "MedicalHistoryService")
    public MedicalHistoryServiceSEI getMedicalHistoryService(WebServiceFeature... features) {
        return super.getPort(MedicalHistoryService, MedicalHistoryServiceSEI.class, features);
    }

}
