// license-header java merge-point
/* Autogenerated on 10/22/2015 21:47:12-0700 by AndroMDA
 *
 * TEMPLATE:    jaxws/WebServiceSEIImplTest.vsl in andromda-webservices-cartridge
 * MODEL CLASS: Data::com.vis.oubl::service::MedicalHistoryService
 * STEREOTYPE:  WebService
 */
package com.vis.oubl.service;

import junit.framework.TestCase;
import junit.textui.TestRunner;

/**
 * WebService Service Delegate Test for the MedicalHistoryService service.
 * 
 */

public class MedicalHistoryServiceSEIImplTest extends TestCase {
	/**
	 * Constructor
	 * 
	 * @param name
	 *            test case name
	 */
	public MedicalHistoryServiceSEIImplTest(String name) {
		super(name);
	}

	/**
	 * No arg Constructor. Delegates to constructor(String) with test case name
	 */
	public MedicalHistoryServiceSEIImplTest() {
		super("MedicalHistoryService");
	}

	/**
	 * @see junit.framework.TestCase#setUp()
	 */
	@Override
	protected void setUp() throws Exception {
		super.setUp();
	}

	/**
	 * @see junit.framework.TestCase#tearDown()
	 */
	@Override
	protected void tearDown() throws Exception {
		super.tearDown();
	}

	/**
	 * Test method for
	 * {@link com.vis.oubl.service.MedicalHistoryServiceSEIImpl#MedicalHistoryServiceSEIImpl()}
	 * .
	 */
	public void testMedicalHistoryServiceSEIImplGetRedPlaneService() {
		// TestCase.setUp and tearDown methods for each individual service
		// method test
		// GetRedPlaneServiceImpl.getRedPlaneServiceSetUp();
		// GetRedPlaneService getRedPlaneServiceInput =
		// GetRedPlaneServiceImpl.getRedPlaneServiceCreateInput();
		// MedicalHistoryServiceSEIImpl delegate = new
		// MedicalHistoryServiceSEIImpl();
		// System.out.println("Invoking MedicalHistoryServiceSEIImpl.getRedPlaneService with "
		// + getRedPlaneServiceInput);
		// / Object rtn = delegate.getRedPlaneService();
		// System.out.println("MedicalHistoryServiceSEIImpl.getRedPlaneService"
		// + " returned " + rtn);
		// GetRedPlaneServiceImpl.getRedPlaneServiceTearDown();
	}

	/**
	 * main() method to run the test with the textual test runner.
	 * 
	 * @param args
	 *            Not used
	 */
	public static void main(final String[] args) {
		TestRunner.run(MedicalHistoryServiceSEIImplTest.class);
	}
}