// license-header java merge-point
/* Autogenerated on 10/22/2015 21:47:12-0700 by AndroMDA
 *
 * TEMPLATE:    jaxws/WebServiceSEIImplTest.vsl in andromda-webservices-cartridge
 * MODEL CLASS: Data::com.vis.oubl::service::SearchService
 * STEREOTYPE:  WebService
*/
package com.vis.oubl.service;

import junit.framework.TestCase;
import junit.textui.TestRunner;

/**
 * WebService Service Delegate Test for the SearchService service.
 * 
 */

public class SearchServiceSEIImplTest extends TestCase
{
    /**
     * Constructor
     * @param name test case name
     */
    public SearchServiceSEIImplTest(String name)
    {
        super(name);
    }

    /**
     * No arg Constructor. Delegates to constructor(String) with test case name
     */
    public SearchServiceSEIImplTest()
    {
        super("SearchService");
    }

    /**
     * @see junit.framework.TestCase#setUp()
     */
    @Override
    protected void setUp() throws Exception
    {
        super.setUp();
    }

    /**
     * @see junit.framework.TestCase#tearDown()
     */
    @Override
    protected void tearDown() throws Exception
    {
        super.tearDown();
    }

    /**
     * Test method for {@link com.vis.oubl.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplCreateCustomer()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        CreateCustomerImpl.createCustomerSetUp();
        CreateCustomer createCustomerInput = CreateCustomerImpl.createCustomerCreateInput();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.createCustomer with " + createCustomerInput);
            Integer rtn = delegate.createCustomer(
             createCustomerInput.getPatient()  // com.vis.oubl.vo.My010CustomerVO
        );
        System.out.println("SearchServiceSEIImpl.createCustomer" + " returned " + rtn);
        CreateCustomerImpl.createCustomerTearDown();
    }

    /**
     * Test method for {@link com.vis.oubl.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplCustomerSearch()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
     //   CustomerSearchImpl.customerSearchSetUp();
    //    CustomerSearch customerSearchInput = CustomerSearchImpl.customerSearchCreateInput();
    //    SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
    //    System.out.println("Invoking SearchServiceSEIImpl.customerSearch with " + customerSearchInput);
    //        Object rtn = delegate.customerSearch(
   //          customerSearchInput.getId()  // Integer
   //     );
   //     System.out.println("SearchServiceSEIImpl.customerSearch" + " returned " + rtn);
   //     CustomerSearchImpl.customerSearchTearDown();
    }

    /**
     * Test method for {@link com.vis.oubl.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplCustomersQuery()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        CustomersQueryImpl.customersQuerySetUp();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.customersQuery");
            Object rtn = delegate.customersQuery(
        );
        System.out.println("SearchServiceSEIImpl.customersQuery" + " returned " + rtn);
        CustomersQueryImpl.customersQueryTearDown();
    }

    /**
     * Test method for {@link com.vis.oubl.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplDeleteCustomer()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        DeleteCustomerImpl.deleteCustomerSetUp();
        DeleteCustomer deleteCustomerInput = DeleteCustomerImpl.deleteCustomerCreateInput();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.deleteCustomer with " + deleteCustomerInput);
            Integer rtn = delegate.deleteCustomer(
             deleteCustomerInput.getId()  // java.lang.Long
        );
        System.out.println("SearchServiceSEIImpl.deleteCustomer" + " returned " + rtn);
        DeleteCustomerImpl.deleteCustomerTearDown();
    }

    /**
     * Test method for {@link com.vis.oubl.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplUpdateCustomer()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        UpdateCustomerImpl.updateCustomerSetUp();
        UpdateCustomer updateCustomerInput = UpdateCustomerImpl.updateCustomerCreateInput();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.updateCustomer with " + updateCustomerInput);
            Integer rtn = delegate.updateCustomer(
             updateCustomerInput.getPatient()  // com.vis.oubl.vo.My010CustomerVO
        );
        System.out.println("SearchServiceSEIImpl.updateCustomer" + " returned " + rtn);
        UpdateCustomerImpl.updateCustomerTearDown();
    }

    /**
     * main() method to run the test with the textual test runner.
     * @param args Not used
     */
    public static void main(final String[] args)
    {
        TestRunner.run(SearchServiceSEIImplTest.class);
    }
}